"""add is_archived

Revision ID: 5ee92a7f26cd
Revises: bc95d3786df6
Create Date: 2026-09-22 19:29:45.322160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee92a7f26cd'
down_revision: Union[str, Sequence[str], None] = 'bc95d3786df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'is_archived')
    # ### end Alembic commands ###
