"""rename archived to hidden

Revision ID: 74a344fc6a0b
Revises: 5ee92a7f26cd
Create Date: 2026-09-22 20:15:40.523353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74a344fc6a0b'
down_revision: Union[str, Sequence[str], None] = '5ee92a7f26cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='notes',
        column_name='is_archived',
        new_column_name='is_hidden'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='notes',
        column_name='is_hidden',
        new_column_name='is_archived'
    )
    # ### end Alembic commands ###
