"""add userid in notes

Revision ID: e8861a916da7
Revises: c46f9c44216a
Create Date: 2026-09-29 15:32:49.274923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8861a916da7'
down_revision: Union[str, Sequence[str], None] = 'c46f9c44216a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'notes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # Замените 'fk_notes_user_id_users' на реальное имя внешнего ключа
    op.drop_constraint('notes_user_id_fkey', 'notes', type_='foreignkey')
    op.drop_column('notes', 'user_id')
    # ### end Alembic commands ###
